### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by CherishineNi** [wizyoung/YOLOv3_TensorFlow#33]
Train. Py file running error, I hope you can help, thank you!

 File "D:\Tensorflow yolov3\YOLOv3_TensorFlow-master\utils\data_utils.py", line 142, in parse_data
    img, boxes = resize_image_and_correct_boxes(img, boxes, img_size)

  File "D:\Tensorflow yolov3\YOLOv3_TensorFlow-master\utils\data_utils.py", line 53, in resize_image_and_correct_boxes
    boxes[:, 0] = boxes[:, 0] / ori_width * new_width

IndexError: too many indices for array

**Comment by changzhiluo** [comment]
This happens when the 'boxes' is an empty list. If you used the following two lines：
`line = str(line)`
`line = line[2:len(line)-2]`
suggested by someone else, just print the _line_ variable to see if it is what you want. In my case, the correct ones are:
`line = str(line)`
`line = line[2:len(line)-1]`.

**Comment by smoolya17** [comment]
How do you debug the tensorflow code?
