### ISSUE TITLE
speed question

### ISSUE THREAD

**Issue by james5551** [wizyoung/YOLOv3_TensorFlow#47]
Hello, your project is doing very well. Thank you very much. However, there was a problem with my speed during the test. I trained my own training set with only one category.When testing a picture, I need 2.4s, which is much worse than your test time. I also tried to put model and nms in front of the session in test_single_image.py, but it still has no effect. what should I do?（By the way, my tensorflow version is 1.11.0 ，with the cuda  9.0 and cudnn 7.）

**Comment by wizyoung** [comment]
I think test_single_image.py cannot be used to measure the speed as it only takes one image as input. If you try batch test by adding a for loop，you will find the speed at the start is kind of slow，which I think is caused by tensorflow. So I used the video_test script to measure the speed. Anyway，I will keep on watching this issue. But now I have no time for that.

**Comment by wizyoung** [comment]
The first image will take a lot of time. I just tested 10 images in a for loop, the time cost is:
```
2623.04902077
28.8169384003
29.2549133301
26.9999504089
28.8610458374
28.0549526215
28.1419754028
28.5141468048
28.6440849304
29.492855072
```
