### ISSUE TITLE
question about convert .weight to .ckpt or .pb

### ISSUE THREAD

**Issue by shenyingying** [wizyoung/YOLOv3_TensorFlow#9]
thanks for your great job,I need convert .ckpt.meta or .pb to .dlc file
but i just have .weight,
use your convert_weight.py ,it can success convert to .ckpt
but i can't convert to .dlc, it just need some node,this is the node,
![node](https://github.com/shenyingying/resource/blob/master/pic/convert_ckpt.png?raw=true)
why it different to [link](https://github.com/mystic123/tensorflow-yolo-v3) 
can you give me some advise,thank you so much.

**Comment by wizyoung** [comment]
Sorry I'm not familiar with dlc conversion. But I guess the problem is due to the node prefix? Please refer to [Line 41 & 44](https://github.com/wizyoung/YOLOv3_TensorFlow/blob/master/model.py#L41), I added two variable scopes called "darknet53_body" and "yolov3_head". May the repo you are referring uses different names.
